CREATE TABLE IF NOT EXISTS "teams" (
    "id" SERIAL PRIMARY KEY,
    "year" INTEGER,
    "name" VARCHAR(255),
    "park" VARCHAR(255)
);
INSERT INTO teams VALUES(1,1884,'Altoona Mountain City',NULL);
INSERT INTO teams VALUES(2,2001,'Anaheim Angels','Edison International Field');
INSERT INTO teams VALUES(3,2001,'Arizona Diamondbacks','Bank One Ballpark');
INSERT INTO teams VALUES(4,2001,'Atlanta Braves','Turner Field');
INSERT INTO teams VALUES(5,1874,'Baltimore Canaries','Newington Park');
INSERT INTO teams VALUES(6,1873,'Baltimore Marylands','Newington Park');
INSERT INTO teams VALUES(7,1884,'Baltimore Monumentals',NULL);
INSERT INTO teams VALUES(8,1889,'Baltimore Orioles','Oriole Park');
INSERT INTO teams VALUES(9,1891,'Baltimore Orioles','Union Park');
INSERT INTO teams VALUES(10,1899,'Baltimore Orioles','Union Park');
INSERT INTO teams VALUES(11,1902,'Baltimore Orioles','Oriole Park');
INSERT INTO teams VALUES(12,2001,'Baltimore Orioles','Oriole Park at Camden Yards');
INSERT INTO teams VALUES(13,1915,'Baltimore Terrapins',NULL);
INSERT INTO teams VALUES(14,1952,'Boston Braves','Braves Field');
INSERT INTO teams VALUES(15,2001,'Boston Red Sox','Fenway Park II');
INSERT INTO teams VALUES(16,1875,'Boston Red Stockings','South End Grounds I');
INSERT INTO teams VALUES(17,1884,'Boston Reds',NULL);
INSERT INTO teams VALUES(18,1890,'Boston Reds',NULL);
INSERT INTO teams VALUES(19,1891,'Boston Reds','Congress Street Grounds');
INSERT INTO teams VALUES(20,1875,'Brooklyn Atlantics','Union Grounds');
INSERT INTO teams VALUES(21,1889,'Brooklyn Bridegrooms','Washington Park I');
INSERT INTO teams VALUES(22,1957,'Brooklyn Dodgers','Ebbets Field');
INSERT INTO teams VALUES(23,1872,'Brooklyn Eckfords','Union Grounds');
INSERT INTO teams VALUES(24,1890,'Brooklyn Gladiators','Ridgewood Park');
INSERT INTO teams VALUES(25,1915,'Brooklyn Tip-Tops',NULL);
INSERT INTO teams VALUES(26,1890,'Brooklyn Ward''s Wonders',NULL);
INSERT INTO teams VALUES(27,1885,'Buffalo Bisons','Olympic Park I');
INSERT INTO teams VALUES(28,1890,'Buffalo Bisons',NULL);
INSERT INTO teams VALUES(29,1915,'Buffalo Blues',NULL);
INSERT INTO teams VALUES(30,1996,'California Angels','Anaheim Stadium');
INSERT INTO teams VALUES(31,2001,'Chicago Cubs','Wrigley Field');
INSERT INTO teams VALUES(32,1890,'Chicago Pirates',NULL);
INSERT INTO teams VALUES(33,1915,'Chicago Whales','Wrigley Field');
INSERT INTO teams VALUES(34,2001,'Chicago White Sox','Comiskey Park II');
INSERT INTO teams VALUES(35,1871,'Chicago White Stockings','Union Base-Ball Grounds');
INSERT INTO teams VALUES(36,1875,'Chicago White Stockings','23rd Street Grounds');
INSERT INTO teams VALUES(37,1884,'Chicago/Pittsburgh (Union League)',NULL);
INSERT INTO teams VALUES(38,1891,'Cincinnati Kelly''s Killers','East End Park');
INSERT INTO teams VALUES(39,1884,'Cincinnati Outlaw Reds',NULL);
INSERT INTO teams VALUES(40,1889,'Cincinnati Red Stockings','League Park I in Cincinnati');
INSERT INTO teams VALUES(41,1880,'Cincinnati Reds','Bank Street Grounds');
INSERT INTO teams VALUES(42,2001,'Cincinnati Reds','Cinergy Field');
INSERT INTO teams VALUES(43,1884,'Cleveland Blues','Kennard Street Park');
INSERT INTO teams VALUES(44,1888,'Cleveland Blues','National League Park II');
INSERT INTO teams VALUES(45,1872,'Cleveland Forest Citys','National Association Grounds');
INSERT INTO teams VALUES(46,2001,'Cleveland Indians','Jacobs Field');
INSERT INTO teams VALUES(47,1890,'Cleveland Infants',NULL);
INSERT INTO teams VALUES(48,1899,'Cleveland Spiders','League Park I');
INSERT INTO teams VALUES(49,2001,'Colorado Rockies','Coors Field');
INSERT INTO teams VALUES(50,1884,'Columbus Buckeyes','Recreation Park I');
INSERT INTO teams VALUES(51,1891,'Columbus Solons','Recreation Park II');
INSERT INTO teams VALUES(52,2001,'Detroit Tigers','Comerica Park');
INSERT INTO teams VALUES(53,1888,'Detroit Wolverines','Recreation Park');
INSERT INTO teams VALUES(54,1873,'Elizabeth Resolutes','Waverly Fairgrounds');
INSERT INTO teams VALUES(55,2001,'Florida Marlins','Pro Player Stadium');
INSERT INTO teams VALUES(56,1871,'Fort Wayne Kekiongas','Hamilton Field');
INSERT INTO teams VALUES(57,1875,'Hartford Dark Blues','Hartford Ball Club Grounds');
INSERT INTO teams VALUES(58,1877,'Hartford Dark Blues','Union Grounds (Brooklyn)');
INSERT INTO teams VALUES(59,2001,'Houston Astros','Enron Field');
INSERT INTO teams VALUES(60,1878,'Indianapolis Blues','South Street Park');
INSERT INTO teams VALUES(61,1884,'Indianapolis Hoosiers','Seventh Street Park');
INSERT INTO teams VALUES(62,1889,'Indianapolis Hoosiers','Athletic Park II');
INSERT INTO teams VALUES(63,1914,'Indianapolis Hoosiers',NULL);
INSERT INTO teams VALUES(64,1967,'Kansas City Athletics','Municipal Stadium I');
INSERT INTO teams VALUES(65,1884,'Kansas City Cowboys',NULL);
INSERT INTO teams VALUES(66,1886,'Kansas City Cowboys','Association Park');
INSERT INTO teams VALUES(67,1889,'Kansas City Cowboys','Exposition Park');
INSERT INTO teams VALUES(68,1915,'Kansas City Packers',NULL);
INSERT INTO teams VALUES(69,2001,'Kansas City Royals','Kauffman Stadium');
INSERT INTO teams VALUES(70,1875,'Keokuk Westerns','Perry Park');
INSERT INTO teams VALUES(71,1964,'Los Angeles Angels','Dodger Stadium');
INSERT INTO teams VALUES(72,2001,'Los Angeles Dodgers','Dodger Stadium');
INSERT INTO teams VALUES(73,1891,'Louisville Colonels','Eclipse Park I');
INSERT INTO teams VALUES(74,1899,'Louisville Colonels','Eclipse Park II');
INSERT INTO teams VALUES(75,1877,'Louisville Grays','Louisville Baseball Park');
INSERT INTO teams VALUES(76,1872,'Middletown Mansfields','Mansfield Club Grounds');
INSERT INTO teams VALUES(77,1965,'Milwaukee Braves','County Stadium');
INSERT INTO teams VALUES(78,1884,'Milwaukee Brewers',NULL);
INSERT INTO teams VALUES(79,1891,'Milwaukee Brewers','Athletic Field');
INSERT INTO teams VALUES(80,1901,'Milwaukee Brewers','Lloyd Street Grounds');
INSERT INTO teams VALUES(81,1997,'Milwaukee Brewers','County Stadium');
INSERT INTO teams VALUES(82,2001,'Milwaukee Brewers','Miller Park');
INSERT INTO teams VALUES(83,1878,'Milwaukee Grays','Eclipse Park II');
INSERT INTO teams VALUES(84,2001,'Minnesota Twins','Hubert H Humphrey Metrodome');
INSERT INTO teams VALUES(85,2001,'Montreal Expos','Stade Olympique');
INSERT INTO teams VALUES(86,1875,'New Haven Elm Citys','Hamilton Park');
INSERT INTO teams VALUES(87,1890,'New York Giants',NULL);
INSERT INTO teams VALUES(88,1957,'New York Giants','Polo Grounds IV');
INSERT INTO teams VALUES(89,1887,'New York Metropolitans','St. George Cricket Grounds');
INSERT INTO teams VALUES(90,2001,'New York Mets','Shea Stadium');
INSERT INTO teams VALUES(91,1875,'New York Mutuals','Union Grounds (Brooklyn)');
INSERT INTO teams VALUES(92,1876,'New York Mutuals','Union Grounds (Brooklyn)');
INSERT INTO teams VALUES(93,2001,'New York Yankees','Yankee Stadium II');
INSERT INTO teams VALUES(94,1915,'Newark Pepper',NULL);
INSERT INTO teams VALUES(95,2001,'Oakland Athletics','Oakland Coliseum');
INSERT INTO teams VALUES(96,1875,'Philadelphia Athletics','Jefferson Street Grounds');
INSERT INTO teams VALUES(97,1876,'Philadelphia Athletics','Jefferson Street Grounds');
INSERT INTO teams VALUES(98,1890,'Philadelphia Athletics',NULL);
INSERT INTO teams VALUES(99,1891,'Philadelphia Athletics','Athletic Park');
INSERT INTO teams VALUES(100,1954,'Philadelphia Athletics','Connie Mack Stadium');
INSERT INTO teams VALUES(101,1875,'Philadelphia Centennials','Centennial Grounds');
INSERT INTO teams VALUES(102,1884,'Philadelphia Keystones',NULL);
INSERT INTO teams VALUES(103,2001,'Philadelphia Phillies','Veterans Stadium');
INSERT INTO teams VALUES(104,1875,'Philadelphia Whites','Jefferson Street Grounds');
INSERT INTO teams VALUES(105,1886,'Pittsburg Alleghenys','Recreation Park');
INSERT INTO teams VALUES(106,1890,'Pittsburgh Burghers',NULL);
INSERT INTO teams VALUES(107,2001,'Pittsburgh Pirates','PNC Park');
INSERT INTO teams VALUES(108,1915,'Pittsburgh Rebels',NULL);
INSERT INTO teams VALUES(109,1885,'Providence Grays','Messer Street Grounds');
INSERT INTO teams VALUES(110,1884,'Richmond Virginians','Allen Pasture');
INSERT INTO teams VALUES(111,1890,'Rochester Broncos','Culver Field I');
INSERT INTO teams VALUES(112,1871,'Rockford Forest Citys','Agricultural Society Fair Grounds');
INSERT INTO teams VALUES(113,2001,'San Diego Padres','Qualcomm Stadium');
INSERT INTO teams VALUES(114,2001,'San Francisco Giants','PacBell Park');
INSERT INTO teams VALUES(115,2001,'Seattle Mariners','Safeco Field');
INSERT INTO teams VALUES(116,1969,'Seattle Pilots','Sicks Stadium');
INSERT INTO teams VALUES(117,1875,'St. Louis Brown Stockings','Grand Avenue Park');
INSERT INTO teams VALUES(118,1877,'St. Louis Brown Stockings','Sportsman''s Park I');
INSERT INTO teams VALUES(119,1891,'St. Louis Browns','Sportsman''s Park I');
INSERT INTO teams VALUES(120,1953,'St. Louis Browns','Sportsman''s Park IV');
INSERT INTO teams VALUES(121,2001,'St. Louis Cardinals','Busch Stadium II');
INSERT INTO teams VALUES(122,1884,'St. Louis Maroons',NULL);
INSERT INTO teams VALUES(123,1886,'St. Louis Maroons','Sportsman''s Park I');
INSERT INTO teams VALUES(124,1875,'St. Louis Red Stockings','Red Stocking Baseball Park');
INSERT INTO teams VALUES(125,1915,'St. Louis Terriers',NULL);
INSERT INTO teams VALUES(126,1884,'St. Paul White Caps',NULL);
INSERT INTO teams VALUES(127,1879,'Syracuse Stars','Newell Park');
INSERT INTO teams VALUES(128,1890,'Syracuse Stars','Star Park II');
INSERT INTO teams VALUES(129,2001,'Tampa Bay Devil Rays','Tropicana Field');
INSERT INTO teams VALUES(130,2001,'Texas Rangers','The Ballpark at Arlington');
INSERT INTO teams VALUES(131,1884,'Toledo Blue Stockings','League Park');
INSERT INTO teams VALUES(132,1890,'Toledo Maumees','Speranza Park');
INSERT INTO teams VALUES(133,2001,'Toronto Blue Jays','Skydome');
INSERT INTO teams VALUES(134,1872,'Troy Haymakers','Haymakers'' Grounds');
INSERT INTO teams VALUES(135,1882,'Troy Trojans','Troy Ball Club Grounds');
INSERT INTO teams VALUES(136,1873,'Washington Blue Legs','Olympics Grounds');
INSERT INTO teams VALUES(137,1872,'Washington Nationals','Nationals Grounds');
INSERT INTO teams VALUES(138,1875,'Washington Nationals','Olympics Grounds');
INSERT INTO teams VALUES(139,1884,'Washington Nationals',NULL);
INSERT INTO teams VALUES(140,1884,'Washington Nationals','Athletic Park');
INSERT INTO teams VALUES(141,1889,'Washington Nationals','Swampdoodle Grounds');
INSERT INTO teams VALUES(142,1872,'Washington Olympics','Olympics Grounds');
INSERT INTO teams VALUES(143,1899,'Washington Senators','Boundary Field');
INSERT INTO teams VALUES(144,1960,'Washington Senators','Griffith Stadium II');
INSERT INTO teams VALUES(145,1971,'Washington Senators','R.F.K. Stadium');
INSERT INTO teams VALUES(146,1891,'Washington Statesmen','Boundary Field');
INSERT INTO teams VALUES(147,1884,'Wilmington Quicksteps',NULL);
INSERT INTO teams VALUES(148,1882,'Worcester Ruby Legs','Worcester Driving Park Grounds');